# datasource
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3307/c0018134?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    username: c0018134
#    password: oathSky=Anon
#    driver-class-name: com.mysql.cj.jdbc.Driver